name       : kaccounts-providers
version    : 21.04.3
release    : 43
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.3/src/kaccounts-providers-21.04.3.tar.xz : 3fb4d1039559bdb47f2c56aa1c8069270dd26ca0651e7c213faa730d8bdc041d
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : KDE Providers
description: |
    KDE providers for accounts sign-on Provides additional configuration files for libaccounts and libsignon to recognize online services such as Facebook and Google.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(signond)
    - kaccounts-integration-devel
    - kdeclarative-devel
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
