name       : kaccounts-providers
version    : 22.04.0
release    : 51
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.0/src/kaccounts-providers-22.04.0.tar.xz : 297a55bcfa26379e9501b70f17da238a4ae23fd908b3afaa0052853a1cca0e34
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : KDE Providers
description: |
    KDE providers for accounts sign-on Provides additional configuration files for libaccounts and libsignon to recognize online services such as Facebook and Google.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(signond)
    - kaccounts-integration-devel
    - kdeclarative-devel
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
