name       : kaccounts-providers
version    : 21.08.3
release    : 47
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/kaccounts-providers-21.08.3.tar.xz : 99c10671b985c0479f403982d467ebd2683992ebcbc043910af70d7e10950a32
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : KDE Providers
description: |
    KDE providers for accounts sign-on Provides additional configuration files for libaccounts and libsignon to recognize online services such as Facebook and Google.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(signond)
    - kaccounts-integration-devel
    - kdeclarative-devel
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
