name       : kaccounts-providers
version    : 20.12.2
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/kaccounts-providers-20.12.2.tar.xz : 804905e0ccedf53ba9c334a4a488cffeaaa5ea5bf983949565a67f3be6a00508
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : KDE Providers
description: |
    KDE providers for accounts sign-on Provides additional configuration files for libaccounts and libsignon to recognize online services such as Facebook and Google.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(signond)
    - kaccounts-integration-devel
    - kdeclarative-devel
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
