name       : kaccounts-providers
version    : 18.08.2
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/kaccounts-providers-18.08.2.tar.xz : 847e77e0eb0c9b8b4ad5cb645e08f6619b0218f8ca62cf9b6985c069dd2a69f6
license    : GPL-2.0-or-later
component  : programming.library
summary    : KDE Providers
description: |
    KDE providers for accounts sign-on Provides additional configuration files for libaccounts and libsignon to recognize online services such as Facebook and Google.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(libaccounts-glib)
    - pkgconfig(Qt5Qml)
    - pkgconfig(signond)
    - extra-cmake-modules
    - kaccounts-integration-devel
    - kcoreaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
