name       : kaccounts-providers
version    : 20.12.1
release    : 37
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.1/src/kaccounts-providers-20.12.1.tar.xz : 78a32db7363b44dae0670f50c68febea6698f57ef3d676a745eb542e87c96fb8
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : KDE Providers
description: |
    KDE providers for accounts sign-on Provides additional configuration files for libaccounts and libsignon to recognize online services such as Facebook and Google.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(signond)
    - kaccounts-integration-devel
    - kdeclarative-devel
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
