name       : kaccounts-providers
version    : 21.12.0
release    : 48
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/kaccounts-providers-21.12.0.tar.xz : 5121c11837830b234a563ff9a9a0fa8051bfbaa781cc115d9e3760a07f8e7078
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : KDE Providers
description: |
    KDE providers for accounts sign-on Provides additional configuration files for libaccounts and libsignon to recognize online services such as Facebook and Google.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(signond)
    - kaccounts-integration-devel
    - kdeclarative-devel
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
