name       : kaccounts-providers
version    : 20.08.0
release    : 31
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.0/src/kaccounts-providers-20.08.0.tar.xz : 5a2293e124839dec3ca5cbe72548ff01ce3c0f7edc5c6dd78ca4d8a27054f574
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : KDE Providers
description: |
    KDE providers for accounts sign-on Provides additional configuration files for libaccounts and libsignon to recognize online services such as Facebook and Google.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(libaccounts-glib)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(signond)
    - extra-cmake-modules
    - kaccounts-integration-devel
    - kdeclarative-devel
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
