name       : kaccounts-providers
version    : 23.04.0
release    : 57
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/kaccounts-providers-23.04.0.tar.xz : cf37813acf5b1895d5a6d2315c60f186ccd7b798ef7bb3b0ad98bd6e29547b1e
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : KDE Providers
description: |
    KDE providers for accounts sign-on Provides additional configuration files for libaccounts and libsignon to recognize online services such as Facebook and Google.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(signond)
    - kaccounts-integration-devel
    - kdeclarative-devel
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
