name       : kaccounts-providers
version    : 21.12.3
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/kaccounts-providers-21.12.3.tar.xz : a09eed6a35e5f1909e4f8cdb9016ed0cd1fb33c34f5545f4c1e2a005d4dd9e4d
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : KDE Providers
description: |
    KDE providers for accounts sign-on Provides additional configuration files for libaccounts and libsignon to recognize online services such as Facebook and Google.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(signond)
    - kaccounts-integration-devel
    - kdeclarative-devel
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
