name       : kaccounts-providers
version    : 21.08.1
release    : 45
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.1/src/kaccounts-providers-21.08.1.tar.xz : e0365b037483273ccfeef19b4840db2ab9e1d4b9910fc588a3e14ed5913fb3f0
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : KDE Providers
description: |
    KDE providers for accounts sign-on Provides additional configuration files for libaccounts and libsignon to recognize online services such as Facebook and Google.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(signond)
    - kaccounts-integration-devel
    - kdeclarative-devel
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
