name       : kaccounts-providers
version    : 18.08.1
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.1/src/kaccounts-providers-18.08.1.tar.xz : a7ad762e925d1ce97abbd2d6a0b0b1b1b3f25910a6aee8b430cbb8eecaf6f179
license    : GPL-2.0-or-later
component  : programming.library
summary    : KDE Providers
description: |
    KDE providers for accounts sign-on Provides additional configuration files for libaccounts and libsignon to recognize online services such as Facebook and Google.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(libaccounts-glib)
    - pkgconfig(Qt5Qml)
    - pkgconfig(signond)
    - extra-cmake-modules
    - kaccounts-integration-devel
    - kcoreaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
