name       : kaccounts-providers
version    : 19.08.2
release    : 19
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/kaccounts-providers-19.08.2.tar.xz : d5ad6882ff151d2f0cff2b76a83e38cf37c72a0dbdf4a0aff64420903266a309
license    : GPL-2.0-or-later
component  : programming.library
summary    : KDE Providers
description: |
    KDE providers for accounts sign-on Provides additional configuration files for libaccounts and libsignon to recognize online services such as Facebook and Google.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(libaccounts-glib)
    - pkgconfig(Qt5Qml)
    - pkgconfig(signond)
    - extra-cmake-modules
    - kaccounts-integration-devel
    - kdeclarative-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
