name       : kaccounts-providers
version    : 20.12.3
release    : 39
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/kaccounts-providers-20.12.3.tar.xz : ae71cadebff1e16991c48fcb9c71c177e2fc2d04536b89d1437587bcdae70617
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : KDE Providers
description: |
    KDE providers for accounts sign-on Provides additional configuration files for libaccounts and libsignon to recognize online services such as Facebook and Google.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(signond)
    - kaccounts-integration-devel
    - kdeclarative-devel
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
