name       : kaccounts-providers
version    : 21.12.1
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/kaccounts-providers-21.12.1.tar.xz : 6413be53fbb2229a55ec73161d53791a7c4e3ccbc70ea1a2e14d8d49a32d948a
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : KDE Providers
description: |
    KDE providers for accounts sign-on Provides additional configuration files for libaccounts and libsignon to recognize online services such as Facebook and Google.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(signond)
    - kaccounts-integration-devel
    - kdeclarative-devel
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
