name       : kaccounts-providers
version    : 22.04.3
release    : 54
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/kaccounts-providers-22.04.3.tar.xz : f2c6c57c7c7306f7751f347eec8f1e483ce5464d3dd22597283dfc84834402e8
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : KDE Providers
description: |
    KDE providers for accounts sign-on Provides additional configuration files for libaccounts and libsignon to recognize online services such as Facebook and Google.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(signond)
    - kaccounts-integration-devel
    - kdeclarative-devel
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
