name       : kaccounts-providers
version    : 20.08.3
release    : 34
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.3/src/kaccounts-providers-20.08.3.tar.xz : d70d9bb72f12eee5eb13ae16112256eaf588940138778fdb991ac8bf8c19fbee
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : KDE Providers
description: |
    KDE providers for accounts sign-on Provides additional configuration files for libaccounts and libsignon to recognize online services such as Facebook and Google.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(libaccounts-glib)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(signond)
    - extra-cmake-modules
    - kaccounts-integration-devel
    - kdeclarative-devel
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
