name       : kaccounts-providers
version    : 18.04.3
release    : 4
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/kaccounts-providers-18.04.3.tar.xz : 31c5b98ab88f80c260674b8b79ed101bdb5b41c4950873815452d1f16b6d7c5b
license    : GPL-2.0-or-later
component  : programming.library
summary    : KDE Providers
description: |
    KDE providers for accounts sign-on Provides additional configuration files for libaccounts and libsignon to recognize online services such as Facebook and Google.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(gl)
    - pkgconfig(libaccounts-glib)
    - pkgconfig(Qt5Qml)
    - pkgconfig(signond)
    - extra-cmake-modules
    - kaccounts-integration-devel
    - kcoreaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
